apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: $PROMETHEUS_ENDPOINT
    uid: PBFA97CFB590B2093
    jsonData:
      httpMethod: GET
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: $TEMPO_ENDPOINT
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      streamingEnabled:
        search: true
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: $LOKI_ENDPOINT
    basicAuth: false
    isDefault: true
    version: 1
    editable: false