receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlphttp/prometheus:
    endpoint: ${env:PROMETHEUS_ENDPOINT}
    tls:
        insecure: true
  otlp/tempo:
    endpoint: ${env:TEMPO_ENDPOINT}
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: ${env:LOKI_ENDPOINT}
  
service:
  pipelines:
    traces:
      receivers: [otlp]
      #processors: [batch]
      exporters:
        - otlp/tempo
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: 
        - otlphttp/loki
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - otlphttp/prometheus
